In [2]:
import numpy as np

In [5]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [7]:
b=np.array([[6,7],[8,9]])
b

array([[6, 7],
       [8, 9]])

In [9]:
addition=a+b
addition

array([[ 7,  9],
       [11, 13]])

In [11]:
dot=np.dot(a,b)
dot

array([[22, 25],
       [50, 57]])

In [12]:
muli=a*b
muli

array([[ 6, 14],
       [24, 36]])

In [13]:
ele=a@b
ele

array([[22, 25],
       [50, 57]])